### ISSUE TITLE
Issues with back navigation button

### ISSUE THREAD

**Issue by michael-tharrington** [forem/ForemWebView-android#68]
**Describe the bug**
One of our long-time moderators, @thomasbnt, pointed out that they’re having mixed results with the back button in the Android app and they outlined a test pattern which I followed and confirmed I was getting the same results.

**To Reproduce**

Just follow these steps:
1. Open the app
2. Click on any post
3. Try to use the back button with a hand gesture OR back button at the bottom of the screen (depending on your phone setting)
4. Exit the Forem app without closing it (just go to an another app or the home screen of your phone)
5. Go back to the Forem app
6. Click on any post
7. Try to use the back button
8. It works now

**Expected behavior**
Using the back button (whether using a sliding hand gesture or the old school buttons on the bottom) should generally work.

**Screenshots**
I'm tagging in @thomasbnt to share some video!

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 
 - Version: 13

**Comment by thomasbnt** [comment]
![Preview Forem App with the bug](https://user-images.githubusercontent.com/14293805/198376185-c084e8b0-3d32-450c-8f51-8e7d99820d8d.mp4)

On **Pixel 6a**. 
Forem App version :  **1.0.12**

**Comment by fdocr** [comment]
Thanks for the report! I'm going to transfer this issue to a different repo so it can be handled there

cc @mirie @rt4914 for visibility

**Comment by rt4914** [comment]
Thanks @fdocr

**Comment by rt4914** [comment]
@michael-tharrington @thomasbnt 
I have investigated this issue fully and sadly I have to say that we cannot do anything in this.
This issue is fore sure because of **Chrome** & **Android-WebView**

Our Forem app shows our websites using **Android-WebView** in application directly and at the core of it, **Google-chrome** is getting used.

Now with latest version of chrome, like `107.0.5304.105` and Android API 31 the Forem app's back button does not work correctly.
Other examples are:
Chrome `107.0.5304.141` -> working correctly on Android API 33 and does not work correctly on Android API 31
Chrome `101.0.4951.74` -> working correctly on Android API 33

**Suggested possible solution**
Because of this dependency on Android-WebView and Google Chrome we actually cannot fix it.

The best possible solution can be to update the Google Chrome app in user's device to fix this bug. (Might not work always because of dependency on Android WebView too.)
